//console.log('O primeiro programa a gente nunca esquece!');
//console.log('Nome Completo: Mara Paula Gonçalves Soares');
//console.log('Endereço: Rua Engenheiro Roberto Magno de Carvalho, 80 fundos - Deodoro');
//console.log('CEP: 21.670-060' + 'Telefone: 21970476945');
//console.log('Deus mais uma vez segura em minha mão\n Minha alma aflita pede sua atenção\n Cheguei ao nível mais difícil até aqui\n Me ajude a concluir');
//console.log('ALUNO (A)   NOTA');
//console.log('=================');
//console.log('ALINE       9.0');
//console.log('MÁRIO       DEZ');
//console.log('SÉRGIO      4.5');
//console.log('SHIRLEY     7.0');
//console.log('CADASTRO DE CLIENTES');
//console.log('0 - Fim');
//console.log('1 - Final');
//console.log('2 - Altera');
//console.log('3 - Exclui');
//console.log('4 - Consulta');
//const opcao = +prompt('Digite uma opção da lista acima: ');
//console.log(`Você escolheu a opção ${opcao}`);
